Add images ( index, catalog, catalog-item)
Dani-kama/homework_binabox pull request #12
Opened 2024-09-08 17:17 UTC by Dani-kama

added images to all pages of the site

2024-09-10 19:35 UTC, fogrew requested changes
You did homework very well! Thank you!

> [!CAUTION]
> ❤️ 3.3. Image Insertion.

❌ You used absolute paths, so all images and other resources are broken on Github Pages.

> [!IMPORTANT]
> 💛 3.6. Optimize images for browser rendering.

Images are optimized almost everywhere! It's very good! But you can do a bit more:
* if you re-export images of steps as SVG instead of png, it would save more bytes for users
* `road_map_decorative_image1.jpg` looks significantly more heavy than others. I tried to optimize it and saved ~90%.

> [!NOTE]
> 💚 1.6. Favicon icons display correctly.

❌ There's no favicon in the markup at all, browser is using default globe icon. User will can't find a tab with your page across other tabs in this case.

> [!TIP]
> 💚 3.7 Use vector sprites where applicable.

✅ I see a lot of optimized combined SVG icons. There's some other that I recommended to put into sprite, but I see you're doing it correct.

> [!TIP]
> 💛 2.9. Elements with background images should have a matching background color.

✅ You didn't used background images at all, so there's no space for color then.

> [!TIP]
> ❤️ 3.1. Correct Image Format

✅ Yes, you used SVG where it's applicable and converted raster images to webp.

> [!TIP]
> ❤️ 3.2. Extract images without style filters from the design.

✅ There's nothing useless in icons

> [!TIP]
> ❤️ 3.4. Specify dimensions for all images.

✅ Sizes is specified everywhere

> [!TIP]
> ❤️ 3.5 Provide alt text for all images.

✅ You provided `alt` everywhere 👏🏻

2024-09-10 19:35 UTC, fogrew commented on catalog-item.html
> +    <link rel="stylesheet" href="/css/normalize.css">
I see you removed directory part of path. In future your websites usually will be located in the root of the domain and for them it's a good move. But for now your website is hosted not on `https://dani-kama.github.io/` address, but on `https://dani-kama.github.io/homework_binabox/`, in sub-directory. It how Github Pages works.

It means that by removing the project prefix, you broke all the paths [on your website](https://dani-kama.github.io/homework_binabox/). If you open DevTools there on Console tab (Windows/Linux: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd> / MacOS: <kbd>Cmd</kbd>+<kbd>Option</kbd>+<kbd>J</kbd>), you will see a lot of errors.

<img width="911" alt="image" src="https://github.com/user-attachments/assets/58e93c94-85c8-4806-b69e-81eff4445456">

So you need to understand what to do in such cases:

**Absolute paths**
Now you used `/css/normalize.css` path, it is absolute path, because started with slash. It's called forward slash. When browser will see such URLs, it will always load files starting from the root domain folder.

Examples if your CSS fill be `/css/style.css`:
| Website | Will be loaded from
| --- | ---
| `https://doma.in/` | ✅ `https://doma.in/css/style.css`
| `https://sub.doma.in/` | ✅ `https://sub.doma.in/css/style.css`
| `https://doma.in/website/` | ❌ `https://doma.in/css/style.css`
| `https://doma.in/website/blog/article/` | ❌ `https://doma.in/css/style.css`
| `https://sub.doma.in/website/` | ❌ `https://sub.doma.in/css/style.css`

Last three rows contain not expected "will be loaded from" value if your website is hosted in sub-directory.

**Relative paths**
If you use `css/style.css` without forward slash, path will be relative. It means that browser will look for this file related of your page. If the HTML file will be in `/blog/` directory, browser will look for `/blog/css/normalize.css` and of course it will return an error `404 Not Found`.

Examples if your CSS file will be `css/style.css` (without forward slash):
| Website | Will be loaded from
| --- | ---
| `https://doma.in/` | ✅ `https://doma.in/css/style.css`
| `https://sub.doma.in/` | ✅ `https://sub.doma.in/css/style.css`
| `https://doma.in/website/` | ✅ `https://doma.in/website/css/style.css`
| `https://doma.in/website/blog/` | ❌ `https://doma.in/website/blog/css/style.css`
| `https://sub.doma.in/website/` | ✅ `https://sub.doma.in/website/css/style.css`

With related paths all resources in website directory will be loaded correctly. But we'll again meet the problem on other levels of sub-directories.

To fix the issue you can use relative paths everywhere and control how they will be rendered via checking pages after pushing any HTML code. It will fix the issue and this is enough. But I would recommend more useful way…

**Base tag**
What you can do to fix this issue is using `<base>` HTML tag in the `<head>` and use relative paths. It will change how relative paths are working. 
```html
<base href="/website/">
```
With `<base>` tag on all pages including project sub-directories like `https://doma.in/website/blog/article/` all resources with relative paths like `css/style.css` will be loaded as absolute (because <base> href attribute was set as absolute path) starting with /website/, so CSS file will be loaded as `/website/css/style.css` as it expected here.

You PR can combine relative paths with `<base>` tag and relative paths for all resources (styles and  images).
```suggestion
    <base href="/homework_binabox/">
    <link rel="stylesheet" href="css/normalize.css">
```

I'm not sure how you're looking at website locally.
* If you using some live server extensions for VS code or something like this, you can commit this way and change the line locally to ` <base href="/">` or remove the line completely. Don't commit this change then.
* Another option is having locally the same directories structure as on Github Pages. You can run live server in parent directory instead of project directory, so for this local server you will have same paths as on Github Pages.

2024-09-10 19:35 UTC, fogrew commented on catalog-item.html
> +        <a href="/index.html" class="logo-img"><img src="/img/logos/logo_binabox.svg" alt="binabox logo" width="36" height="40"><span class="logo-img-text">Binabox</span></a>
> [!TIP]
> 💚 3.7 Use vector sprites where applicable

It is okay to load the logo separately, but if you load all images at the same time, browser will spend less time for establishing connection with the server. Absolutely not critical, you can ignore it if you want (in this case please answer something like "I want to use it as is"). As for me, it would be better to move all the SVGs into sprite.

2024-09-10 19:35 UTC, fogrew commented on catalog-item.html
> +                    <use href="/img/sprite.svg#sun" alt=""></use>
You moved graphics from raster format to vector, and even moved it into sprite. It's good 👍🏻

And you used `alt`. It's good to describe what is on image by text in this attribute[^1].
It's bad to leave it empty[^2].

But the main issue here that you don't need to add `alt` attribute to `<use>` tag. It's unsupported[^3]. `alt` is applicable only to images.

You want to make the icon readable for screen readers, you can provide `aria-label` attribute for some parent tag[^4]. In terms of UX (user experience) icon is additional information about the place where it's used.
If you're using a button with icon, you can add `aria-label` to button. Screen reader will read the text of this button anyway, so you don't need to add additional explanation to button if text sounds meaningful. But if there's no text in a button, then `aria-label` is required[^5]. It will help to make button accessible for people who can see it by some reason (blindness, driving, automatic parsing).

By the way, you have icons without text in this file (see arrows). You can try to apply this attribute there if you want.

**You can read more:**
[^1]: MDN article [Images in HTML → Alternative text](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML#alternative_text)
[^2]: MDN article [`<img>` tag page with valid attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attributes)
[^3]: MDN article [`<use>` tag with valid attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use)
[^4]: Article [Icon accessibility and aria label](https://gomakethings.com/icon-accessibility-and-aria-label/) by [Chris Ferdinandi](https://gomakethings.com/about/)
[^5]: Article [Icon buttons should be labelled with aria-label](https://medium.com/100-days-in-kyoto-to-create-a-web-app-with-google/day-16-icon-buttons-should-be-labelled-with-aria-label-1056515d3707) by [Masa Kudamatsu](https://masakudamatsu.dev/)

2024-09-10 19:35 UTC, fogrew commented on catalog-item.html
> +                    <svg width="19" height="32" viewBox="0 0 19 32" fill="none" xmlns="http://www.w3.org/2000/svg">
You don't need to add `xmlns` attribute when inserting SVG into the HTML, because it's declaration of standard about how browser should render this content, but HTML5 already including SVG standard, so browsers will understand it even without `xmlns` attribute. It's not a mistake, just useless extra attribute.

I would recommend to remove it.

Or you can choose some other way how to render this icon:
* move the icon into a sprite. Your `stroke` assignment in `styles.css` will work properly anyway.
* you can achieve the same visual with using SVG as a path with `fill` instead of `stroke`. It may be more lightweight in result.
* you can do it without SVG at all by rotating a square block with top and right borders (or any other sibling borders) with `rotate: 45deg` (same as `transform: rotate(45deg)`

Do whatever you want with it 🚀

2024-09-10 19:35 UTC, fogrew commented on catalog.html
> +            <button class="btn-discord-footer"><svg class="button-discord-ico" width="24" height="19">
> [!WARNING]
> Code style note, not really important

Would be better to start all new tags from new line to increase readability as part of DX (developer experience). It's usually applicable to all tags, most teams doing it with all tags. But some teams have an agreement to newline tags only if they're inline in semantic (not block) like `<span>`. Until you're working alone in repository, you can choose code style for yourself, but you it would be better to comply it anyway. It's good practice.

2024-09-10 19:35 UTC, fogrew commented on catalog.html
> +                            </svg>
You used `width` and `height` attributes on `<use>` tag. It's valid in terms of HTML validity. This way you specify size of used symbol from the sprite. But it's wrong if you want to specify entire SVG icon size.

I would recommend you to move sizes to parent `<svg>` tag.

p.s. you're using a lot of extra spaces, it's also bad practice in terms of code style as in previous comment.

```suggestion
                            <svg class="social-link-ico" width="18" height="16">
                                <use href="/img/sprite.svg#xtwi"></use>
                            </svg>
```

2024-09-10 19:35 UTC, fogrew commented on css/styles.css
> +    text-transform: capitalizeupp;
Looks like there is a typo, right?

```suggestion
    text-transform: capitalize;
```

or you wanted to make it CAPS?

```suggestion
    text-transform: uppercase;
```

2024-09-10 19:35 UTC, fogrew commented on css/styles.css
> +
You chosen good way. Styling `fill` attribute is the best approach for SVG icons because only this way allows you to change the color smoothly via for example `transition: fill .2s ease-out`.

This method doesn't work here because you applied this class (`r-map-btns-arrows`) to `<button>` tag in markup. If you move specify SVG, it should help (or you can specify classname of icons instead of tag)

```suggestion
.r-map-btns-arrows:hover svg {
    fill: #21E786;
}
```

2024-09-10 19:35 UTC, fogrew commented on css/styles.css
> +    content: url("data:image/svg+xml;charset=UTF-8,<svg xmlns='http://www.w3.org/2000/svg' height='30' width='30'><circle cx='15' cy='15' r='15' fill='%2321E786' fill-opacity='0.2' /> <circle cx='15'
Whoa!) I want to say bravo for knowing all ways how to insert the image 👏🏻

If you want to inline SVGs, I recommend to do it with [URL-encoder](https://yoksel.github.io/url-encoder/).

It will not only escape (replace with url-safe) `#` by `%23`, but also [do some other transformations](https://github.com/yoksel/url-encoder/blob/master/src/js/script.js#L134-L148): 
* Escape quotes
* Escape opening and closing angle brackets (`<` and `>`)
* Escape these symbols `%()?[`
* Remove extra new lines

Otherwise browser may skip your image.

Another thing what you can do is moving this icons into sprite as well. Then you can insert them from HTML markup or use here in styles via `url()` function
```suggestion
    content: url("img/sprite.svg#active-point");
```
Or you can combine these ways, but I won't suggest this way, because it's difficult to support:
```css
    content: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='30' width='30'%3E%3Cuse href='img/sprite.svg%23active-point'/%3E%3C/svg%3E")
```

2024-09-10 19:35 UTC, fogrew commented on img/sprite.svg
> +        <symbol id="ds"  viewBox="0 0 28 20" fill="none">
> [!TIP]
> Another code style tip, not really important

In all companies where I worked we had a rule to not use shorthands in filenames or class names or id's.
Nobody knows after a years what did you mean by this "ds" naming. Maybe it's "data servers"? Maybe "Daniel Superman", maybe "DartS", who knows :) 

So, general recommendation here is to use full names of everything. Browsers can compress repeated words in text files like SVG or HTML, so there's no need to save some bytes for user via naming. But you will help other developers in your team to understand what mean "ds" symbol in huge svg sprite.

2024-09-10 19:35 UTC, fogrew commented on img/stepicons/step1ico.png
I think step icons may be an SVG icons, what do you think?

2024-09-10 19:35 UTC, fogrew commented on img/road_map_decorative_image1.jpg
This image may be optimized almost on 90%, could you please try to compress it via something? For example, I'm using [squoosh.app](https://squoosh.app/)

2024-09-14 12:31 UTC, Dani-kama commented on img/stepicons/step1ico.png
I was considering this option. but then I noticed that png is 10 times smaller than svg. And since most likely these elements are not designed for stretching and even in zoom format on different displays they still look good. 
Or is it better to use svg here anyway without looking at the size?


<img hiegth="50">![Снимок экрана 2024-09-14 152251](https://github.com/user-attachments/assets/b495ede2-b381-49aa-a899-89bda472fd7e)

2024-09-16 17:39 UTC, fogrew commented on img/stepicons/step1ico.png
If you can't compress it more, it's okay to use PNG.

There's one thing which you can take into account:
People with retina screens will see raster images a bit blurred if image with same sizes as container where it's placed. If you want to imagine how it will look just decrease dimensions of image twice and stretch it back via CSS. It will look how people with retina screens see your image. In my experience we always preferred to use at least 2x scaled images, which means using `<picture>` (or `<img>` with `srcset` attribute). After that compression for some people image will weight less than vector one, but for some people more. [Worldwide statistics of retina screens](https://gs.statcounter.com/screen-resolution-stats) is still not huge, even if we [filter it only by desktops](https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide). But their amount grows from year to year.

2024-12-02 17:36 UTC, TalDmitrii commented on catalog-item.html
> +        <a href="/index.html" class="logo-img"><img src="/img/logos/logo_binabox.svg" alt="binabox logo" width="36" height="40"><span class="logo-img-text">Binabox</span></a>
I recommend you to join Logo SVG with "Binabox" text, and export it together as the SVG.

2024-12-02 17:38 UTC, TalDmitrii commented on catalog-item.html
> +                <picture class="selected-img-item">
In this course we only use WEBP and SVG formats.

2024-12-02 17:39 UTC, TalDmitrii commented on catalog-item.html
> +                    <figure class="carusel-items">
Nice usage of Figure tag 👍

2024-12-02 17:42 UTC, TalDmitrii commented on css/styles.css
> +.phase-items>p::before {
We need to add class attributes to all tags, and then use classes for styling. For example:

.phase-items>p::before ==> .phase-text::before

2024-12-06 18:05 UTC, TalDmitrii commented on css/styles.css
> +.r-map-btns-arrows:hover svg {
Здесь ты пытаешься покрасить сам тег SVG, но если мы взглянем на это в sprite.svg, то мы увидим, что на самом деле здесь красится тег PATH, при помощи атрибута stroke:
`<path d="M12.5 3L7.50003 8L2.5 3" stroke="white" stroke-width="3" stroke-miterlimit="10" stroke-linecap="square" stroke-linejoin="round" />`

2024-12-06 18:22 UTC, TalDmitrii commented on css/styles.css
> +.r-map-btns-arrows:hover svg {
Чтобы решить эту проблему, мы устанавливаем значение currentColor для атрибута stroke.
`<path d="M12.5 3L7.50003 8L2.5 3" stroke="currentColor" stroke-width="3" stroke-miterlimit="10" stroke-linecap="square" stroke-linejoin="round" />`
После этого тег PATH покраситься в цвет, установленный на кнопке.

2024-12-06 18:25 UTC, TalDmitrii commented on css/styles.css
> +.r-map-btns-arrows:hover svg {
Следующим шагом мы устанавливаем нужное нам значение цвета на кнопке.
По дизайну нам нужен белый цвет.
`.r-map-btns-arrows {
    border: none;
    background-color: transparent;
    color: white;
}`

2024-12-06 18:26 UTC, TalDmitrii commented on css/styles.css
> +.r-map-btns-arrows:hover svg {
И добавляем изменение цвета при ховере:
`.r-map-btns-arrows:hover {
    color: yellow;
}`

2024-12-13 17:50 UTC, merged